@startuml user_activity_login
start
:Click login;
:Redirect to Github B2C authentication;
:Enter Github credentials;
if (user exists?) then (yes)
else (no)
:Redirect to B2C user details page;
:Verify email;
endif
:Redirect to public timeline;
stop
@enduml