@startuml user_activity_unauthenticated
skin rose

title Unauthorized - activity diagram

start
:Display Public Timeline;
:Click on a Username;
:Redirect to User's Timeline;
:Display User's Timeline;
:Go to Next/Previous Page;
stop

@enduml
