@startuml
skin rose

title Unauthorized - activity diagram

start
:Display Public Page;
:Click on a Username;
:Redirect to User's Timeline;
:Display User's Timeline;
:Go to Next/Previous Page;
stop

@enduml
