name: Autorelease

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          
        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 7.0.x
        - name: Restore dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore
        - name: Test
          run: dotnet test --no-build --verbosity normal
    
    autorelease:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Setup dotnet
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 7.0.401

            - name: Build executables
              shell: bash
              run: |
                tag=$(git describe --tags --abbrev=0)

                # Build everything
                dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime "linux-x64" Release -o "Chirp-$tag-linux-x64"
                # Build everything
                dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime "win-x64" Release -o "Chirp-$tag-win-x64"
                # Build everything
                dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime "osx-x64" Release -o "Chirp-$tag-osx-x64"

                # Pack to zip for Windows
                7z a -tzip "Chirp-$tag-windows.zip" "./Chirp-$tag-win-x64"
                7z a -tzip "Chirp-$tag-linux.zip" "./Chirp-$tag-linux-x64"
                7z a -tzip "Chirp-$tag-macos.zip" "./Chirp-$tag-osx-x64"


                # Delete output directory
                rm -r "Chirp-$tag-win-x64"
                rm -r "Chirp-$tag-linux-x64"
                rm -r "Chirp-$tag-osx-x64"

            - name: Publish
              uses: softprops/action-gh-release@v1
              with:
                files: "Chirp*"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}