name: Autorelease

on:
  push:
    tags:
      - "v*.*.*"

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 7.0.x
        - name: Restore dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore
        - name: Test
          run: dotnet test --no-build --verbosity normal
    
    autorelease:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup dotnet
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 7.0.x

            - name: Build Windows
              shell: bash
              run: |
                tag=$(git describe --tags --abbrev=0)
                windows_release_name=Chirp-$tag-win-x64
                
                # Build everything
                dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime "win-x64" -c Release -o "${windows_release_name}"
    
                7z a -tzip "${windows_release_name}.zip" "./${windows_release_name}/*"
                
                # Delete output directory
                rm -r "$windows_release_name"

            - name: Build Linux
              shell: bash
              run: |
                tag=$(git describe --tags --abbrev=0)
                linux_release_name=Chirp-$tag-linux-x64
                      
                # Build everything
                dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime "linux-x64" -c Release -o "${linux_release_name}"
    
                tar czvf "${linux_release_name}.tar.gz" "$linux_release_name"
                
                # Delete output directory
                rm -r "$linux_release_name"

            - name: Build MacOS
              shell: bash
              run: |
                tag=$(git describe --tags --abbrev=0)
                macOS_release_name=Chirp-$tag-osx-x64
                
                # Build everything
                dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime "osx-x64" -c Release -o "${macOS_release_name}"
    
                tar czvf "${macOS_release_name}.tar.gz" "$macOS_release_name"
                
                # Delete output directory
                rm -r "$macOS_release_name"

            - name: Build MacOS Arm
              shell: bash
              run: |
                tag=$(git describe --tags --abbrev=0)
                macOS_arm_release_name=Chirp-$tag-osx-arm64
                
                # Build everything
                dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime "osx-arm64" -c Release -o "${macOS_arm_release_name}"
    
                tar czvf "${macOS_arm_release_name}.tar.gz" "$macOS_arm_release_name"
                
                # Delete output directory
                rm -r "$macOS_arm_release_name"

            - name: Publish
              uses: softprops/action-gh-release@v1
              with:
                files: "Chirp*"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
