name: Autorelease

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          
        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 7.0.x
        - name: Restore dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore
        - name: Test
          run: dotnet test --no-build --verbosity normal
    
    autorelease:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Setup dotnet
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 7.0.401

            - name: Build executables
              shell: bash
              run: |
                tag=$(git describe --tags --abbrev=0)

                # Build everything (Windows)
                dotnet publish -r win-x64 --self-contained false
                # Build everything (Linux)
                dotnet publish -r linux-x64 --self-contained false
                # Build everything (MacOS)
                dotnet publish -r osx-x64 --self-contained false
                # Build everything (MacARM)
                dotnet publish -r osx-arm64 --self-contained false

                # Pack to zip for Windows
                7z a -tzip "Chirp-$tag-windows.zip" "./Chirp-$tag-windows/*"
                7z a -tzip "Chirp-$tag-linux.zip" "./Chirp-$tag-linux/*"
                7z a -tzip "Chirp-$tag-macos.zip" "./Chirp-$tag-macos/*"

                # Delete output directory
                rm -r "Chirp-$tag-windows"
                rm -r "Chirp-$tag-linux"
                rm -r "Chirp-$tag-macos"

            - name: Publish
              uses: softprops/action-gh-release@v1
              with:
                files: "App*"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}