name: Autorelease

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          
        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 7.0.x
        - name: Restore dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore
        - name: Test
          run: dotnet test --no-build --verbosity normal
    
    autorelease:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Setup dotnet
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 7.0.401

            - name: Build executables
              shell: bash
              run: |
                tag=$(git describe --tags --abbrev=0)

                # Build everything
                dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --os win -c Release -o "Chirp-$tag-windows/src/Chirp.CLI"
                # Build everything
                dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --os linux -c Release -o "Chirp-$tag-linux/src/Chirp.CLI"
                # Build everything
                dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --os osx -c Release -o "Chirp-$tag-macos/src/Chirp.CLI"

                # Add CSV-file
                mkdir "App-$tag-windows/data/"
                mkdir "App-$tag-linux/data/"
                mkdir "App-$tag-macos/data/"

                cp "data/chirp_cli_db.csv" "App-$tag-windows/data/"
                cp "data/chirp_cli_db.csv" "App-$tag-linux/data/"
                cp "data/chirp_cli_db.csv" "App-$tag-macos/data/"

                # Pack to zip for Windows
                7z a -tzip "App-$tag-windows.zip" "./App-$tag-windows/*"
                7z a -tzip "App-$tag-linux.zip" "./App-$tag-linux/*"
                7z a -tzip "App-$tag-macos.zip" "./App-$tag-macos/*"


                # Delete output directory
                rm -r "App-$tag-windows"
                rm -r "App-$tag-linux"
                rm -r "App-$tag-macos"

            - name: Publish
              uses: softprops/action-gh-release@v1
              with:
                files: "App*"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}