# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Autodeploy to Azure

env:
    WEBAPP_PACKAGE_PATH: "src/Chirp.Razor"
    WEBAPP_INFRA_PATH: "src/Chirp.Infrastructure"
    RESOURCE_GROUP: "bdsagroup15chirprazor_group"
    WEBAPP_NAME: "bdsagroup15chirprazor"
    DOTNET_CONFIG: "Release"

on:
    push:
        branches:
            - main
        paths-ignore:
            - "*.md"
    workflow_dispatch:

jobs:
    build:
        name: "Build Code"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name:
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "7.0.x"

            - name: Build
              run: dotnet build ${{ env.WEBAPP_PACKAGE_PATH }} --configuration ${{ env.DOTNET_CONFIG }}

            - name: Publish
              run: dotnet publish ${{ env.WEBAPP_PACKAGE_PATH }} -c ${{ env.DOTNET_CONFIG }} --no-build

            - name: Upload Application
              uses: actions/upload-artifact@v3
              with:
                  name: Chirp.Razor
                  path: ${{env.WEBAPP_PACKAGE_PATH }}/bin/${{env.DOTNET_CONFIG}}/net7.0/publish

            - name: Install EF Tool
              run: dotnet tool install --global dotnet-ef

            - name: Build Migrations Bundle
              run: dotnet ef migrations bundle -p ${{env.WEBAPP_INFRA_PATH }} -s ${{env.WEBAPP_PACKAGE_PATH }} -c ${{ env.DOTNET_CONFIG }} --no-build --self-contained

            - name: Upload Migrations Bundle
              uses: actions/upload-artifact@v3
              with:
                  name: efbundle
                  path: efbundle

    deploy:
        name: "Deploy to Azure"
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v3
              with:
                  name: .net-app

            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v3
              with:
                  app-name: "bdsagroup15chirprazor"
                  slot-name: "Production"
                  publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CEA05D565A284343AA3F002DF3A70770 }}
                  package: .
